fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt":
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.8.0"
    "portage": "git://github.com/gentoo/puppet-portage.git"
    "chocolatey": "git://github.com/rismoney/puppet-chocolatey.git"
    "epel": "git://github.com/stahnma/puppet-module-epel.git"
    "gpg_key": "git://github.com/treydock/puppet-gpg_key.git"
  symlinks:
    "nodejs": "#{source_dir}"
